version: '3'
services:
  server:
    container_name: "server"
    build:
      context: Container1
      dockerfile: Dockerfile
    ports:
      - "20022:2000"
      - "11211:11211"

  client:
    container_name: "client"
    build:
      context: Container2
      dockerfile: Dockerfile
    ports:
      - "10022:10022"





#	client:
#    build:

